
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
        sudo apt-get update -qq;
    else
        brew update;
    fi

script:
  - make

notifications:
  email: false
   
